language : generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources


before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libglew-dev
- curl -R -O http://www.lua.org/ftp/lua-5.3.3.tar.gz
- tar zxf lua-5.3.3.tar.gz
- cd lua-5.3.3
- sudo make linux install MYCFLAGS='-fPIC'
- cd ../
- git clone https://github.com/glfw/glfw.git
- cd glfw
- cmake .
- sudo make install
- cd ../


compiler :
  - gcc-5


script : 
  - mkdir build
  - cd build
  - cmake .. && make