language : generic
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
      - cmake
      - cmake-data
    sources: &sources
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3



before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libglew-dev
- git submodule init && git submodule update
- curl -R -O http://www.lua.org/ftp/lua-5.3.3.tar.gz
- tar zxf lua-5.3.3.tar.gz
- cd lua-5.3.3
- sudo make linux install MYCFLAGS='-fPIC'
- cd ../
- cd extlib/glfw
- cmake .
- sudo make install
- cd ../freetype2
- mkdir build
- cd build
- cmake -D BUILD_SHARED_LIBS:BOOL=true .. && make
- cd ../../../ 


compiler :
  - gcc-5


script : 
  - mkdir build
  - cd build
  - cmake .. && make