language : c++
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libglew-dev libglfw-dev
- curl -R -O http://www.lua.org/ftp/lua-5.3.3.tar.gz
- tar zxf lua-5.3.3.tar.gz
- cd lua-5.3.3
- sudo make linux install

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
compiler :
  - g++


script : 
  - mkdir build
  - cd build
  - cmake .. && make