language : c++
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
compiler :
  - g++
  - gcc
  - clang++

script : 
  - mkdir build
  - cd build
  - cmake .. && make