language : generic
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
      - cmake
      - cmake-data
    sources: &sources
      - ubuntu-toolchain-r-test


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenal-dev


compiler :
  - gcc-5


script : 
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SHARED=ON
  - make
