language : c++

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - clang
compiler :
  - gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libglew-dev
- curl -R -O http://www.lua.org/ftp/lua-5.3.3.tar.gz
- tar zxf lua-5.3.3.tar.gz
- cd lua-5.3.3
- sudo make linux install
- cd ../
- git clone https://github.com/glfw/glfw.git
- cd glfw
- cmake .
- sudo make install
- cd ../




script : 
  - mkdir build
  - cd build
  - cmake .. && make