language : generic
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
      - cmake
      - cmake-data
    sources: &sources
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3



before_install:
  - ./Setup.sh

compiler :
  - gcc-5


script : 
  - mkdir build
  - cd build
  - cmake .. && make
