language : generic
env: COMPILER_NAME=gcc CXX=g++-8 CC=gcc-8
addons:
  apt:
    packages:
      - g++-8
    sources: &sources
      - ubuntu-toolchain-r-test


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq


compiler :
  - gcc-8
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.13.1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.13.1-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}


script : 
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SHARED=ON
  - make
