#pragma once

namespace fm {
	enum RENDER_QUEUE {
		RENDER_QUEUE_FIRST_STATE,
		RENDER_QUEUE_BEFORE_RENDERING_FILL_QUEUE,
		RENDER_QUEUE_BACKGROUND,
		RENDER_QUEUE_BEFORE_LIGHT,
		RENDER_QUEUE_OPAQUE,
		RENDER_QUEUE_TRANSPARENT,
		RENDER_QUEUE_LIGHT,
		RENDER_QUEUE_AFTER_LIGHT,
		RENDER_QUEUE_SKYBOX,
		RENDER_QUEUE_OVERLAY,
		RENDER_QUEUE_AFTER_RENDERING,
		RENDER_QUEUE_LAST_STATE
	};
}