name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # Defining Ubuntu and Windows OS
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies (Linux)
        run: sudo apt-get install ninja-build mesa-utils libgl1-mesa-dev libpulse-dev portaudio19-dev libasound2-dev libjack-dev libpipewire-0.3-dev libdbus-1-dev
        if: matrix.os == 'ubuntu-latest'
      - name: configure
        run: cmake . -B build -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build